#define IDC 666
#define NAME Test
#define TITLE Test
BEGIN_WINDOW(IDC,NAME,TITLE,0.5,0.5,5,5)
WINDOW_HEADER(NAME,IDC,TITLE,3)
WINDOW_CLOSE(NAME,IDC,4)
WINDOW_HELP(NAME,IDC,"Test",3)
WINDOW_BACKGROUND(NAME,0,1,5,4)
END_WINDOW