//This file was generated by Map Builder
//To load this objects copy this script to your mission and put
// nil = [] execVM "test.sqf";
//in your init.sqf or a trigger-activation.
private["_obj"];
_obj = "Land_HBarrier_3_F" createvehicle [1765.478149,5682.475098,0];
_obj setposATL [1765.478149,5682.475098,0];
_obj setVectorDirAndUp [[0,1,0],[0,0,1]];
_obj setposATL [1765.478149,5682.475098,0];
_obj = "Land_HBarrier_3_F" createvehicle [1771.236694,5684.520508,0];
_obj setposATL [1771.236694,5684.520508,0];
_obj setVectorDirAndUp [[0,1,0],[0,0,1]];
_obj setposATL [1771.236694,5684.520508,0];
