disableSerialization;
private["_display","_ctrl"];
	_display = uinamespace getvariable 'mb_main_dialog';
	(_display displayCtrl 170101) ctrlShow false;
	(_display displayCtrl 170101) ctrlEnable false;
	(_display displayCtrl 170102) ctrlShow false;
	(_display displayCtrl 170102) ctrlEnable false;
	(_display displayCtrl 170103) ctrlShow false;
	(_display displayCtrl 170103) ctrlEnable false;
	MB_PopupOpen = false;